-- =============================================================
-- MIGRACIÓN DE ESQUEMA A POSTGRESQL (SUPABASE)
-- TABLAS: materiales, estructuras_catalogo, estructuras_mano_obra,
--         uucc_material_estructura, totales_materiales, analisis_costo_estructura
-- =============================================================

-- PASO 4: LIMPIEZA MASIVA DE LAS TABLAS (Si ya existen, vaciamos datos o las recreamos)
DROP TABLE IF EXISTS analisis_costo_estructura CASCADE;
DROP TABLE IF EXISTS locales_materiales CASCADE;
DROP TABLE IF EXISTS totales_materiales CASCADE;
DROP TABLE IF EXISTS uucc_material_estructura CASCADE;
DROP TABLE IF EXISTS estructuras_mano_obra CASCADE;
DROP TABLE IF EXISTS estructuras_catalogo CASCADE;
DROP TABLE IF EXISTS materiales CASCADE;

-- TABLA 1: materiales
CREATE TABLE materiales (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item             INTEGER,
    codigo           INTEGER UNIQUE NOT NULL,
    descripcion      TEXT NOT NULL,
    unidad           TEXT,
    precio_igmelec   NUMERIC,
    precio_grape     NUMERIC,
    precio_bellon    NUMERIC,
    precio_ochoa     NUMERIC,
    precio_maenca    NUMERIC,
    precio_transdeci NUMERIC
);

-- Habilitar RLS permisiva
ALTER TABLE materiales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON materiales FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- TABLA 2: estructuras_catalogo
CREATE TABLE estructuras_catalogo (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    tipo   TEXT
);

ALTER TABLE estructuras_catalogo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON estructuras_catalogo FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- TABLA 3: estructuras_mano_obra
CREATE TABLE estructuras_mano_obra (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    precio      NUMERIC,
    itbis       NUMERIC,
    total       NUMERIC
);

ALTER TABLE estructuras_mano_obra ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON estructuras_mano_obra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- TABLA 4: uucc_material_estructura
CREATE TABLE uucc_material_estructura (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estructura       TEXT NOT NULL,
    codigo_material  INTEGER NOT NULL REFERENCES materiales(codigo) ON DELETE CASCADE,
    descripcion      TEXT,
    cantidad         NUMERIC,
    total_uso        NUMERIC
);

ALTER TABLE uucc_material_estructura ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON uucc_material_estructura FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- TABLA 5: totales_materiales 
CREATE TABLE totales_materiales (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_material INTEGER UNIQUE REFERENCES materiales(codigo) ON DELETE CASCADE,
    descripcion     TEXT,
    total           NUMERIC
);

ALTER TABLE totales_materiales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON totales_materiales FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- TABLA 6: analisis_costo_estructura
CREATE TABLE analisis_costo_estructura (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estructura      TEXT,
    codigo_material INTEGER REFERENCES materiales(codigo) ON DELETE CASCADE,
    descripcion     TEXT,
    cantidad        NUMERIC,
    unidad          TEXT,
    precio_unitario NUMERIC,
    subtotal        NUMERIC GENERATED ALWAYS AS (
        CASE WHEN cantidad IS NOT NULL AND precio_unitario IS NOT NULL
             THEN ROUND(cantidad * precio_unitario, 2)
             ELSE NULL END
    ) STORED
);

ALTER TABLE analisis_costo_estructura ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permissive Policy" ON analisis_costo_estructura FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- =============================================================
-- VISTAS SQL (CREACION)
-- =============================================================

-- Vista 1: Precio de referencia consolidado (prioriza IGMELEC -> GRAPE -> BELLON -> OCHOA)
CREATE OR REPLACE VIEW v_materiales_precio AS
SELECT 
    codigo, 
    descripcion, 
    unidad,
    COALESCE(precio_igmelec, precio_grape, precio_bellon, precio_ochoa, precio_maenca, precio_transdeci) AS precio_referencia
FROM materiales;

-- Vista 2: Costo de materiales por estructura en el análisis detallado
CREATE OR REPLACE VIEW v_costo_por_estructura AS
SELECT 
    estructura, 
    COUNT(*) AS cant_items, 
    ROUND(SUM(subtotal),2) AS costo_materiales_total
FROM analisis_costo_estructura 
WHERE subtotal IS NOT NULL 
GROUP BY estructura;

-- Vista 3: Costo UUCC teórico (usando BOMs y precio base)
CREATE OR REPLACE VIEW v_costo_uucc_por_estructura AS
SELECT 
    u.estructura, 
    COUNT(DISTINCT u.codigo_material) AS materiales_distintos,
    SUM(u.cantidad) AS cantidad_total,
    ROUND(SUM(u.cantidad * COALESCE(m.precio_igmelec, m.precio_grape, 0)), 2) AS costo_materiales_rd
FROM uucc_material_estructura u
LEFT JOIN materiales m ON u.codigo_material = m.codigo
GROUP BY u.estructura 
ORDER BY costo_materiales_rd DESC;

-- Vista 4: Uso total x precio para priorizar compras
CREATE OR REPLACE VIEW v_materiales_uso_total AS
SELECT 
    t.codigo_material,
    m.descripcion,
    t.total AS cantidad_total,
    COALESCE(m.precio_igmelec, m.precio_grape, 0) AS precio_unitario,
    ROUND(t.total * COALESCE(m.precio_igmelec, m.precio_grape, 0), 2) AS costo_total_proyectado
FROM totales_materiales t
JOIN materiales m ON t.codigo_material = m.codigo
ORDER BY costo_total_proyectado DESC;
